=== mmbase/mmbase.github.io/xmlns/blocktypes.xsd
<?xml version="1.0"?>
<!--
  @version $Id: blocktypes.xsd,v 1.1 2008-03-25 09:20:24 michiel Exp $
-->
<xsd:schema
    xmlns="http://www.mmbase.org/xmlns/blocktypes"
    targetNamespace="http://www.mmbase.org/xmlns/blocktypes"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    version="1.0"
    >

  <xsd:import
      namespace="http://www.w3.org/XML/1998/namespace"
      schemaLocation="http://www.w3.org/2001/03/xml.xsd"
      />


  <xsd:element name="blocktypes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="blocktype"    minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="blocktype">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="title"       minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attribute name="weight" type="xsd:integer"  />
      <xsd:attribute name="name" type="xsd:string"  />
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="title">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="xml:lang" />
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>


</xsd:schema>

=== mmbase/mmbase.github.io/components/blocktypes.xml
<?xml version="1.0" ?>
<blocktypes
    xmlns="http://www.mmbase.org/xmlns/blocktypes"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mmbase.org/xmlns/blocktypes
                        http://www.mmbase.org/xmlns/blocktypes.xsd">
  <!--
       The following defines the order or the entries in the /mmbase/admin menu.
       /mmbase/admin shows all block classified in 'mmbase'.
  -->
  <blocktype name="mmbase.about"           weight="0">
    <title xml:lang="nl">Over</title>
    <title xml:lang="en">About</title>
    <title xml:lang="eo">Pri</title>
  </blocktype>
  <blocktype name="mmbase.admin"           weight="10" >
    <title xml:lang="nl">Beheer</title>
    <title xml:lang="en">Admin</title>
    <title xml:lang="eo">Estrado</title>
  </blocktype>
  <blocktype name="mmbase.tools"           weight="20">
    <title xml:lang="nl">Gereedschap</title>
    <title xml:lang="en">Tools</title>
    <title xml:lang="eo">Iloj</title>
  </blocktype>
  <blocktype name="mmbase.components"      weight="30">
    <title xml:lang="nl">Componenten</title>
    <title xml:lang="en">Components</title>
    <title xml:lang="eo">Kombineroj</title>
  </blocktype>

  <blocktype name="mmbase.edit"            weight="40">
    <title xml:lang="nl">Redactie</title>
    <title xml:lang="en">Edit</title>
    <title xml:lang="eo">Redakto</title>
  </blocktype>

  <blocktype name="mmbase.documentation" weight="50">
    <title xml:lang="nl">Documentatie</title>
    <title xml:lang="en">Documentation</title>
    <title xml:lang="eo">Dokumentado</title>
  </blocktype>

  <blocktype name="mmbase.examples"        weight="10000">
    <title xml:lang="nl">Voorbeelden</title>
    <title xml:lang="en">Examples</title>
    <title xml:lang="eo">Ekzemploj</title>
  </blocktype>
</blocktypes>
